### ISSUE TITLE
Error starting up

### ISSUE THREAD

**Issue by KyleMassacre** [AndrewWasHere/photobooth#1]
When I run the photobooth command I get this error:

```
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_18-01-13_3.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-67f7dee, 20171204
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170124]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [PhotoboothApp] __init__().
[INFO   ] [State Machine] Initialized to state waiting state.
 Traceback (most recent call last):
   File "photobooth.py", line 180, in <module>
     main()
   File "photobooth.py", line 177, in main
     PhotoboothApp(settings).run()
   File "/home/pi/Desktop/rpicamera/ui/photoboothapp.py", line 61, in __init__
     subprocess.call(shlex.split(cmd))
   File "/usr/lib/python2.7/subprocess.py", line 168, in call
     return Popen(*popenargs, **kwargs).wait()
   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
     errread, errwrite)
   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
     raise child_exception
 OSError: [Errno 2] No such file or directory
```

Sorry if this is noobish. I am new to python and just trying to learn

**Comment by AndrewWasHere** [comment]
Couple of questions:

What did you type on the command line, exactly, to run photobooth?

Did you modify any of the settings in photobooth_defaults.cfg?

It looks like photobooth is crashing on a call to the ImageMagick `convert` command (line 61 of photoboothapp.py. You can see that in the stack trace you posted), so I'm guessing that ImageMagick is not installed on your system. You can check to see if ImageMagick is installed using `which`. You should see something like this:

```
$ which convert
/usr/bin/convert
```

In case you're wondering what's going on in the code there, the command on line 61 is creating the canvas image that gets placed behind the the photos taken by the photobooth when compositing.

**Comment by AndrewWasHere** [comment]
No response to queries. Closing this issue.
